### ISSUE TITLE
Module website not updated for week 13

### ISSUE THREAD

**Issue by shaniceabigail** [nus-cs2103-AY1819S1/cs2103-website#10]
<img width="674" alt="moduleindexissue" src="https://user-images.githubusercontent.com/28746253/48417571-0892a280-e78e-11e8-80fe-93652312eb5d.png">

The website did not update to highlight week 13, as it usually updates, even though it's already Tuesday, Week 13.

**Comment by damithc** [comment]
Thanks for the reminder @shaniceabigail. updated.
