### ISSUE TITLE
Textbook typo

### ISSUE THREAD

**Issue by jonathantjm** [nus-cs2103-AY1819S1/cs2103-website#11]
Link to section: https://nus-cs2103-ay1819s1.github.io/cs2103-website/se-book-adapted/chapters/oop.html#associations

![image](https://user-images.githubusercontent.com/28558009/48725010-d7224700-ec65-11e8-98cf-e65cd49814df.png)

Correction: "classles" should be "classes", as per highlighted

Edit: It's under the "What" subheading

**Comment by damithc** [comment]
Thanks for the bug report @jonathantjm. Fixed.
