### ISSUE TITLE
Textbook multiplicity typo

### ISSUE THREAD

**Issue by jonathantjm** [nus-cs2103-AY1819S1/cs2103-website#12]
Link to section: https://nus-cs2103-ay1819s1.github.io/cs2103-website/se-book-adapted/chapters/oop.html#associations, under the "Multiplicity" subheading

![image](https://user-images.githubusercontent.com/28558009/48725227-79dac580-ec66-11e8-861f-a9516284e4d3.png)

Correction: "navigability" should be "multiplicity", as per highlighted

**Comment by damithc** [comment]
Thanks for the bug report @jonathantjm. Fixed.
