### ISSUE TITLE
Textbook Abstract Classes typo

### ISSUE THREAD

**Issue by jonathantjm** [nus-cs2103-AY1819S1/cs2103-website#13]
Link: https://nus-cs2103-ay1819s1.github.io/cs2103-website/se-book-adapted/chapters/oop.html#abstract-classes

![image](https://user-images.githubusercontent.com/28558009/48725742-0e91f300-ec68-11e8-83b8-3af3153349a8.png)

Correction: "Evan a class" should be "Even a class" (i think?). and the bold needs to be fixed too

**Comment by damithc** [comment]
Thanks for the bug report @jonathantjm. Fixed.
