### ISSUE TITLE
Duplicate question in schedule section W2.5a

### ISSUE THREAD

**Issue by pengnam** [nus-cs2103-AY1819S1/cs2103-website#2]
![image](https://user-images.githubusercontent.com/28092058/44470154-99f4eb80-a65b-11e8-832b-df79f35449f9.png)

**Comment by damithc** [comment]
It's not actually a bug. Evidence section is simply pointing to a question in the exercises section. Usually, evidence is a subset of exercises.
Thanks for raising this issue nevertheless @pengnam
