### ISSUE TITLE
Do we need to use JDK 9 for address book level 1?

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/cs2103-website#4]
According to https://github.com/nus-cs2103-AY1819S1/addressbook-level1/blob/master/docs/DeveloperGuide.adoc#SettingUp.

This should be my current JDK version, but I may be wrong (better check!):
![image](https://user-images.githubusercontent.com/35895966/44477463-4ee3d400-a66d-11e8-8268-460f94fbc6c3.png)
![image](https://user-images.githubusercontent.com/35895966/44477511-70dd5680-a66d-11e8-86d5-06aa97c596b3.png)

When I click "Update Now", it also says that I already have the latest Java platform on the system:
![image](https://user-images.githubusercontent.com/35895966/44477584-a97d3000-a66d-11e8-8909-323da295ab05.png)

And finally when I Google JDK 9 and click on this [link ](https://www.oracle.com/technetwork/java/javase/downloads/jdk9-downloads-3848520.html), it redirects me to download JDK 10 in 20 seconds:
![image](https://user-images.githubusercontent.com/35895966/44477669-e2b5a000-a66d-11e8-8bc3-48b963e6f0c9.png)
![image](https://user-images.githubusercontent.com/35895966/44477688-ed703500-a66d-11e8-92a8-650399dba3dd.png)

Help please! Any help would be appreciated :)

Should I just download JDK 10? Before that, should I also uninstall my current version of Java on my computer first?

Thank you! :D

P.S. When we create an issue on this "issues" forum, a notification to the Slack channel doesn't appear? :o

**Comment by yamgent** [comment]
> Do we need to use JDK 9 for address book level 1?

Yes you will need JDK 9. Please use the following URL to download JDK 9: http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase9-3934878.html. You will need to register an account before downloading JDK 9.

> Should I just download JDK 10? Before that, should I also uninstall my current version of Java on my computer first?

For `addressbook-level1`, if you configure IntelliJ as per the developer guide's instructions, there shouldn't be a need to uninstall Java 8 (you can manually choose which version to be used).

Hope that helps.

**Comment by yamgent** [comment]
Btw, it is recommended for Windows users to use JDK9, rather than the latest JDK10, due to some peculiar issues that you will face with JDK10 when you progress to a higher level of address book (`addressbook-level4` will **definitely need** JDK9 for Windows).

I suggest sticking with 9 so that you won't have to worry about installation problems again for the rest of cs2103. :)

**Comment by eugenepeh** [comment]
For windows user, all your java jdk should be in `C:\Program Files\Java\` by default. 
So please check if it is there.

For IntelliJ, you can select which JDK to use for the project so don't worry.

For command prompt users, often you can change your jdk version for a single instance by doing something like this in the:
`set JAVA_HOME=C:\Program Files\Java\jdk-10.0.1`

For permanent change, do read up this following article:
https://www.java.com/en/download/help/path.xml

**Comment by damithc** [comment]
> something like this in the:
> set JAVA_HOME=C:\Program Files\Java\jdk-10.0.1

Does this need double quotes around it (because of the space in the middle)?

**Comment by ghost** [comment]
Hi, thank you all! I will get to working on it soon! :)

**Comment by ghost** [comment]
Yup I think I have successfully installed JDK 9.

![image](https://user-images.githubusercontent.com/35895966/44508725-ea169100-a6e1-11e8-86f9-e94617c87994.png)

They did tell me a new Java update is available. For Java 10 though, but I think as suggested, I will ignore it :)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/35895966/44509163-6a89c180-a6e3-11e8-8a49-e89a5ccb0106.png)

Btw I realized there are 2 "issues" forum? In future, I should post [here](https://github.com/nus-cs2103-AY1819S1/forum/issues) instead?

For website issues, then I post on the current website [here](https://github.com/nus-cs2103-AY1819S1/cs2103-website/issues/)

**Comment by yamgent** [comment]
> Btw I realized there are 2 "issues" forum? In future, I should post here instead?

Please do for future cs2103 questions, so that your other classmates will be able to see the posts and learn from it too. :)

Btw just wondering, were you trying to ask another question with the picture? Don't see any questions there...

**Comment by damithc** [comment]
> P.S. When we create an issue on this "issues" forum, a notification to the Slack channel doesn't appear? :o

Slack doesn't have that feature anymore in the free version :-(

**Comment by ghost** [comment]
Hi @yamgent, no I was just using that screenshot to show that everything has been configured correctly. Looks like it! :)
