### ISSUE TITLE
Unable to open "Projects List" link

### ISSUE THREAD

**Issue by ghost** [nus-cs2103-AY1819S1/cs2103-website#5]
After clicking on "Projects List" under Links tab of [CS2103/T website](https://nus-cs2103-ay1819s1.github.io/cs2103-website/), the [webpage](https://nus-cs2103-ay1819s1.github.io/cs2103-website/admin/projectList.html) cannot load properly.

Is it supposed to this way? Screenshot of the blank page attached :)

![screenshot](https://user-images.githubusercontent.com/35895966/44509655-e59fa780-a6e4-11e8-86ed-4ce12e4cf546.png)

**Comment by damithc** [comment]
Thanks for bringing this up @HEARTOFAL1ON 
Yes, it's supposed to be a list of projects from the current batch. Will be updated once you guys have started the projects.
