### ISSUE TITLE
Typo in Week 3 LOs

### ISSUE THREAD

**Issue by azhikai** [nus-cs2103-AY1819S1/cs2103-website#7]
Under `Tutorial 3` > `Evidence for Weekly LOs` > `For W3.1c...`:

> Suggested: Do some refactoring to the addressbook-level1 code. Remember to commit after each refactoring. The commit message should mention the refactoring you applied. e.g. AddressBook.java: _extrace_ foo() method

It should be `extract` instead.

![image](https://user-images.githubusercontent.com/7473075/44626601-a88c1d00-a951-11e8-8389-bfc584f63131.png)

**Comment by damithc** [comment]
Thanks for the bug report @AZhiKai 
Will fix in the next update

**Comment by damithc** [comment]
Fixed
