### ISSUE TITLE
IntelliJ not detecting JavaFX

### ISSUE THREAD

**Issue by aaditkamat** [nus-cs2103-AY1819S1/cs2103-website#9]
The javafx package was being detected on IntelliJ and the necessary files correctly imported into the project until recently. Appended below is the screenshot of the errors I am getting. I am not able to find the JAR on the web as suggested by IntelliJ. I tried but couldn't find useful answers for this issue online. Could anyone suggest how I should proceed with troubleshooting this issue?

![screenshot 2018-10-16 at 12 20 28 am](https://user-images.githubusercontent.com/30969577/46963863-4d68e200-d0d9-11e8-87e4-ba36a2f96471.png)

**Comment by damithc** [comment]
@aaditkamat please post help requests in the module forum https://github.com/nus-cs2103-AY1819S1/forum/issues
